export default {
  user: {},

  remains: [
    {
      id: 1,
      tag: 'icon',
      name: '校徽',
      desc: '校徽可以凸显名校背景',
      img: '',
      content: null,
      multiple: true,
    },
    {
      id: 2,
      tag: 'job',
      name: '工作经历',
      num: 2,
      total: 30,
      desc: '展示申请岗位相关的经验与能力',
      img: '',
      content: null,
      multiple: true,
    },
    {
      id: 3,
      tag: 'orgnize',
      name: '社团和组织能力',
      desc: '展现人际交往与团队合作能力',
      img: '',
      content: null,
      multiple: true,
    },
    {
      id: 4,
      tag: 'edu',
      name: '教育经历',
      num: 2,
      total: 30,
      ref: true,
      desc: '介绍学历背景与专业素养',
      img: '',
      content: null,
      multiple: true,
    },
    {
      id: 5,
      tag: 'other',
      name: '其他',
      desc: '突出掌握的技能和证书',
      img: '',
      content: null,
      multiple: true,
    },
    {
      id: 6,
      tag: 'project',
      name: '项目经历',
      num: 2,
      total: 50,
      ref: true,
      desc: '介绍专业领域的项目经验与能力',
      img: '',
      content: null,
      multiple: true,
    },
    {
      id: 7,
      tag: 'research',
      name: '研究经历',
      desc: '展现专业经验与能力',
      img: '',
      content: null,
      multiple: true,
    },
    {
      id: 8,
      tag: 'award',
      name: '荣誉奖项',
      desc: '含金量高的奖项是很好的加分项',
      img: '',
      content: null,
      multiple: true,
    },
    {
      id: 9,
      tag: 'summary',
      name: '个人总结',
      desc: '总结优势，突出亮点',
      img: '',
      content: null,
      multiple: false,
    },
    {
      id: 10,
      tag: 'skill',
      name: '专业技能',
      num: 1,
      total: 50,
      ref: true,
      desc: '列出自己掌握的技能，展示强项',
      img: '',
      content: null,
      multiple: false,
    },
    {
      id: 11,
      tag: 'custom',
      name: '自定义',
      desc: '其他需要自行添加的内容',
      img: '',
      content: null,
      multiple: true,
    },
  ],

  // info: { basic: {}, skill: [], edu: [], project: [], job: [], summary: [] },

  info: {
    basic: {
      imported: [2, 4, 6, 10],
      user: {
        name: { desc: '姓名', value: '' },
        avatar: { desc: '', src: '' },
      },
      contact: {
        telephone: { desc: '电话', value: '' },
        email: { desc: '邮箱', value: '' },
        city: { desc: '现居城市', value: '' },
      },
      social: {
        website: {
          desc: '个人网站',
          value: null,
          placeholder: '如：github.com/wondercv.com',
        },
        linkin: {
          desc: 'LinkedIn',
          value: null,
          placeholder: '如：github.com/wondercv.com',
        },
        wechat: {
          desc: 'wexin',
          value: null,
          placeholder: '如：github.com/wondercv.com',
        },
      },
      other: {
        age: {
          desc: '年龄或生日',
          value: null,
          placeholder: '如：github.com/wondercv.com',
        },
        sex: {
          desc: '性别',
          value: null,
          placeholder: '如：github.com/wondercv.com',
        },
      },
      intension: {
        workIntension: {
          desc: '求职意向',
          value: null,
          placeholder: '如：github.com/wondercv.com',
        },
        currentJob: {
          desc: '当前工作状态',
          value: null,
          placeholder: '如：github.com/wondercv.com',
        },
        expectSalary: {
          desc: '期望薪资',
          value: null,
          placeholder: '如：github.com/wondercv.com',
        },
      },
    },
    skill: {
      ref: true,
      desc: '',
      update: '',
    },
    job: {
      ref: true,
      name: { desc: '公司名称', value: '' },
      timespan: { start: '', end: '' },
      attrs: {
        post: { desc: '职位名称', value: '' },
        department: { desc: '所在部门', value: '' },
      },
      location: { desc: '所在城市', value: '' },
      desc: '',
      update: '',
    },
    project: {
      ref: true,
      name: { desc: '项目名称', value: '' },
      timespan: { start: '', end: '' },
      attrs: {
        post: { desc: '担任角色', value: '' },
      },
      location: { desc: '所在城市', value: '' },
      desc: '',
      update: '',
    },
    edu: {
      ref: true,
      name: { desc: '学校名称', value: '' },
      timespan: { start: '', end: '' },
      attrs: {
        post: { desc: '所学专业', value: '' },
        scholar: { desc: '学历', value: '' },
        department: { desc: '所在学院', value: '' },
      },
      location: { desc: '所在城市', value: '' },

      desc: '',
      update: '',
    },
    summary: { ref: false, desc: '', update: '' },
  },
}
