export default {

  activeId: 1,
  
  formTag: '',

  isScanning: false,

  remains: [
    {
      id: 1,
      tag: 'icon',
      name: '校徽',
      ref: false,
      desc: '校徽可以凸显名校背景',
      img: '',
      content: null,
      multiple: true,
    },
    {
      id: 2,
      tag: 'job',
      name: '实习/工作经历',
      num: 2,
      total: 30,
      ref: true,
      desc: '展示申请岗位相关的经验与能力',
      img: '',
      content: null,
      multiple: true,
    },
    {
      id: 3,
      tag: 'orgnize',
      name: '社团和组织能力',
      ref: false,
      desc: '展现人际交往与团队合作能力',
      img: '',
      content: null,
      multiple: true,
    },
    {
      id: 4,
      tag: 'edu',
      name: '教育经历',
      num: 2,
      total: 30,
      ref: true,
      desc: '介绍学历背景与专业素养',
      img: '',
      content: null,
      multiple: true,
    },
    {
      id: 5,
      tag: 'other',
      name: '其他',
      ref: false,
      desc: '突出掌握的技能和证书',
      img: '',
      content: null,
      multiple: true,
    },
    {
      id: 6,
      tag: 'project',
      name: '项目经历',
      num: 2,
      total: 50,
      ref: true,
      desc: '介绍专业领域的项目经验与能力',
      img: '',
      content: null,
      multiple: true,
    },
    {
      id: 7,
      tag: 'research',
      name: '研究经历',
      ref: false,
      desc: '展现专业经验与能力',
      img: '',
      content: null,
      multiple: true,
    },
    {
      id: 8,
      tag: 'award',
      name: '荣誉奖项',
      ref: false,
      desc: '含金量高的奖项是很好的加分项',
      img: '',
      content: null,
      multiple: true,
    },
    {
      id: 9,
      tag: 'summary',
      name: '个人总结',
      ref: false,
      desc: '总结优势，突出亮点',
      img: '',
      content: null,
      multiple: true,
    },
    {
      id: 10,
      tag: 'skill',
      name: '专业技能',
      num: 1,
      total: 50,
      ref: true,
      desc: '列出自己掌握的技能，展示强项',
      img: '',
      content: null,
      multiple: false,
    },
    {
      id: 11,
      tag: 'custom',
      name: '自定义',
      ref: false,
      desc: '其他需要自行添加的内容',
      img: '',
      content: null,
      multiple: true,
    },
  ],
  
}
